# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/libutils_temp.ipynb (unless otherwise specified).

__all__ = ['export']

# Comes from testscript_temp.ipynb, cell
import sys
def export(fn):
    mod = sys.modules[fn.__module__]
    if hasattr(mod, '__all__'):
        mod.__all__.append(fn.__name__)
    else:
        mod.__all__ = [fn.__name__]
    return fn