# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fun": "testscript_temp.ipynb",
         "main": "testscript_temp.ipynb",
         "export": "testscript_temp.ipynb"}

modules = ["plotter/picture_output.py",
           "utils/libutils.py"]

doc_url = "https://methuselah-0.github.io/nbdev-org-babel-example/"

git_url = "https://github.com/methuselah-0/nbdev-org-babel-example/tree/master/"

def custom_doc_links(name): return None
